### ISSUE TITLE
no link

### ISSUE THREAD

**Issue by bennetho** [sparkz-technology/hackcam#2]
|__   __ _  ___| | __    / ___|  ___ __ _ __ ___        
 | '_ \ / _' |/ __| |/ /    | |    /  _'  | '_ ' _ \       
 | | | | (_| | (__|   <     | |___|  (__| | | | | | |      
 |_| |_|\__,_|\___|_|\_\    \_____|\__,___|_| |_| |_|      
                                                                     
  v1.1 code by sutharsan_sparkz 

[01] Ngrok

[+] Choose a Port Forwarding option: 1

[+] Starting php server...
[+] Starting ngrok server...
[*] Direct link: 

[*] Waiting targets, Press Ctrl + C to exit...

i already setup my ngrok but no link

**Comment by KeparYTbcc** [comment]
Same ![Screenshot_20210919_205838_com.termux.jpg](https://user-images.githubusercontent.com/67996155/133948876-507a9e31-6b27-46a1-a7c6-8f5b4dd3c1ba.jpg)

**Comment by RobertoTrue** [comment]
me pasa igual
